#cross-compiler compilation code taken form OSDev wiki.

language: c

sudo: required
compiler: gcc

before_install:
  - export MAKEFLAGS="-j4"

install:
  - export PREFIX="$HOME/opt/cross"
  - export TARGET=i686-elf
  - export PATH="$PREFIX/bin:$PATH"
  - sudo apt-get install -y libmpfr-dev libmpc-dev libgmp-dev nasm build-essential
  - wget http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.gz
  - tar -xf binutils-2.27.tar.gz
  - mkdir binutils-build
  - cd binutils-build
  - ../binutils-2.27/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
  - make
  - make install
  - wget ftp://ftp.fu-berlin.de/unix/languages/gcc/releases/gcc-6.2.0/gcc-6.2.0.tar.gz
  - tar -xf gcc-6.2.0.tar.gz
  - mkdir gcc-build
  - cd gcc-build
  - ../gcc-6.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c --without-headers
  - make all-gcc
  - make all-target-libgcc
  - make install-gcc
  - make install-target-libgcc

script:
  - make
